name: Java CI

on:
  push:
    branches: ["win"]
  pull_request:
    branches: ["win"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Fetch only the latest commit for faster builds

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Compile Java
        run: |
          cd HolidayTravelVehicles
          mkdir -p bin
          javac -d bin *.java

      - name: Run Main Class
        run: |
          cd HolidayTravelVehicles
          java MainClassName  # Replace MainClassName with your actual main class name
